language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install .
  - pip install -r tests/requirements.txt 
  - pip install -r docs/requirements.txt pytest pytest-cov coveralls
# command to run tests
script:
  - set -e
  - python --version
  - python -m pytest -vv --color=yes --disable-pytest-warnings --cov-config=conf/.coveragerc --cov-report xml:reports/coverage.xml --cov=armodel tests/

after_success:
  - coveralls